export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT'
export const CHANGE_PROMO_CHECKBOX = 'CHANGE_PROMO_CHECKBOX'
export const CHANGE_ACTIVE_CHECKBOX = 'CHANGE_ACTIVE_CHECKBOX'
export const RESIZE_WINDOW = 'RESIZE_WINDOW'
